Repository B3Partners/brmo, pull requests merged in 2018-10, with the labels that each got.

#525 Bump tomcat version 7.0.90 -> 7.0.91
  pom.xml
Labels: Hacktoberfest, dependency update

#516 maven site verbeteringen
  brmo-test-util/pom.xml
  datamodel/pom.xml
  pom.xml
  src/site/markdown/index.md
  src/site/site.xml
Labels: Hacktoberfest :beers:, bouw- en testinfrastuctuur, vraag of documentatie

#533 clean workspace na succesvolle build
  Jenkinsfile
  datamodel/pom.xml
Labels: bouw- en testinfrastuctuur

#534 voeg AutomatischProces id toe aan (entity) laadprocessen
  brmo-loader/src/main/java/nl/b3p/brmo/loader/BrmoFramework.java
  brmo-loader/src/main/java/nl/b3p/brmo/loader/StagingProxy.java
  brmo-loader/src/main/java/nl/b3p/brmo/loader/entity/LaadProces.java
  brmo-service/src/main/java/nl/b3p/brmo/service/scanner/BAGDirectoryScanner.java
  brmo-service/src/main/java/nl/b3p/brmo/service/scanner/BGTLightOphalenProces.java
  brmo-service/src/main/java/nl/b3p/brmo/service/scanner/GDS2OphalenProces.java
  brmo-service/src/main/java/nl/b3p/brmo/service/scanner/WebMirrorBAGDirectoryScanner.java
  brmo-service/src/main/java/nl/b3p/brmo/service/stripes/BasisregistratieBigFileLoadActionBean.java
  brmo-service/src/main/java/nl/b3p/brmo/service/stripes/BasisregistratieFileUploadActionBean.java
  brmo-service/src/main/java/nl/b3p/brmo/service/stripes/BasisregistratieServiceActionBean.java
Labels: Hacktoberfest :beers:, brmo-service, enhancement :+1:

#528 fix: `typering` en `clazz` van een persoon uit de nHR soms voorzien van enkele quotes
  brmo-loader/src/main/resources/xsl/nhr-to-rsgb-xml-3.0.xsl
  brmo-loader/src/test/java/nl/b3p/GH527NhrToStagingToRsgbIntegrationTest.java
  brmo-service/src/main/java/nl/b3p/brmo/service/stripes/AdvancedFunctionsActionBean.java
Labels: Hacktoberfest :beers:, brmo-service, regressie

#546 Laden stadsdeel uit BGT light
  bgt-gml-loader/src/main/java/nl/b3p/brmo/loader/gml/BGTGMLLightTransformerFactory.java
  bgt-gml-loader/src/main/xml/datamodel.xml
  bgt-gml-loader/src/test/java/nl/b3p/brmo/loader/gml/BGTGMLLightLoaderIntegrationTest.java
  bgt-gml-loader/src/test/resources/gmllight/bgt_stadsdeel.gml
  datamodel/upgrade_scripts/1.6.0-1.6.1/oracle/rsgbbgt.sql
  datamodel/upgrade_scripts/1.6.0-1.6.1/postgresql/rsgbbgt.sql
  datamodel/upgrade_scripts/1.6.0-1.6.1/sqlserver/rsgbbgt.sql
Labels: BGT, Hacktoberfest :beers:, brmo-service, enhancement :+1:, rsgbbgt

#542 Fix verschillende regressies in "BGT light" lader
  .gitattributes
  bgt-gml-loader/imgeo-simple-2.1-gml31.xsd.zip
  bgt-gml-loader/src/main/java/nl/b3p/brmo/bgt/util/JDBCDataStoreUtil.java
  bgt-gml-loader/src/main/java/nl/b3p/brmo/loader/gml/BGTGMLLightLoader.java
  bgt-gml-loader/src/main/java/nl/b3p/brmo/loader/gml/BGTGMLLightTransformerFactory.java
  bgt-gml-loader/src/main/xsl/datamodel_ddl.xsl
  bgt-gml-loader/src/test/java/nl/b3p/brmo/loader/gml/BGTGMLLightLoaderIntegrationTest.java
  bgt-gml-loader/src/test/java/nl/b3p/brmo/loader/gml/BGTLightZipsLoaderIntegrationTest.java
  bgt-gml-loader/src/test/java/nl/b3p/brmo/loader/gml/TestingBase.java
  bgt-gml-loader/src/test/resources/gmllight/dated/38468_0-20160422.zip
  bgt-gml-loader/src/test/resources/gmllight/dated/38468_0-20160512.zip
  bgt-gml-loader/src/test/resources/gmllight/one/one.zip
  bgt-gml-loader/src/test/resources/gmllight/schiermonnikoog/57830-57831.zip
  bgt-gml-loader/src/test/resources/gmllight/schiermonnikoog/57830.zip
  bgt-gml-loader/src/test/resources/gmllight/schiermonnikoog/57831.zip
  bgt-gml-loader/src/test/resources/gmllight/two/two.zip
  bgt-gml-loader/src/test/resources/gmllight/zips/extract-gmllight.zip
  bgt-gml-loader/src/test/resources/log4j.xml
  brmo-loader/src/main/java/nl/b3p/brmo/loader/StagingProxy.java
  brmo-loader/src/main/java/nl/b3p/brmo/loader/util/BGTLightRsgbTransformer.java
  brmo-loader/src/test/resources/nl/b3p/brmo/loader/xml/9999MUT02012015-03012015.zip
  brmo-loader/src/test/resources/nl/b3p/brmo/loader/xml/MUTBX01-ASN00T2939A12-20091130-1.zip
  brmo-service/src/test/resources/GH-317-BAG-van-GDS2/DNLDLXAM02-15967-5014117-31032017-01042017.zip
  brmo-stuf/wsdl-resources/tools/XSD-Resolver.zip
  datamodel/upgrade_scripts/1.6.0-1.6.1/oracle/rsgbbgt.sql
  datamodel/upgrade_scripts/1.6.0-1.6.1/postgresql/rsgbbgt.sql
  datamodel/upgrade_scripts/1.6.0-1.6.1/sqlserver/rsgbbgt.sql
  topparser/src/main/resources/nl/b3p/topnl/top100nl/standaardGML/iso/19139/iso19139-20060504.zip
  topparser/src/main/resources/nl/b3p/topnl/top100nl/standaardGML/iso/19139/iso19139-20070417.zip
  topparser/src/main/resources/nl/b3p/topnl/top100nl/standaardGML/xlink/xlink-1_0_0.zip
  topparser/src/main/resources/nl/b3p/topnl/top10nl/standaardGML/iso/19139/iso19139-20060504.zip
  topparser/src/main/resources/nl/b3p/topnl/top10nl/standaardGML/iso/19139/iso19139-20070417.zip
  topparser/src/main/resources/nl/b3p/topnl/top10nl/standaardGML/xlink/xlink-1_0_0.zip
  topparser/src/main/resources/nl/b3p/topnl/top250nl/standaardGML/iso/19139/iso19139-20060504.zip
  topparser/src/main/resources/nl/b3p/topnl/top250nl/standaardGML/iso/19139/iso19139-20070417.zip
  topparser/src/main/resources/nl/b3p/topnl/top250nl/standaardGML/xlink/xlink-1_0_0.zip
  topparser/src/main/resources/nl/b3p/topnl/top50nl/standaardGML/iso/19139/iso19139-20060504.zip
  topparser/src/main/resources/nl/b3p/topnl/top50nl/standaardGML/iso/19139/iso19139-20070417.zip
  topparser/src/main/resources/nl/b3p/topnl/top50nl/standaardGML/xlink/xlink-1_0_0.zip
  wsdl-resources/tools/XSD-Resolver.zip
Labels: BGT, brmo-service, bug :bomb:, regressie

#547 aanpassen git gedrag in appveyor.yml
  .travis.yml
  appveyor.yml
Labels: bouw- en testinfrastuctuur

#552 AppVeyor build matrix aanpassingen
  .travis.yml
  appveyor.yml
  bgt-gml-loader/src/main/java/nl/b3p/brmo/bgt/util/JDBCDataStoreUtil.java
  bgt-gml-loader/src/test/java/nl/b3p/brmo/bgt/util/PDOKBGTLightUtilTest.java
  bgt-gml-loader/src/test/java/nl/b3p/brmo/loader/gml/BGTGMLLightLoaderIntegrationTest.java
  bgt-gml-loader/src/test/java/nl/b3p/brmo/loader/gml/TestingBase.java
  bgt-gml-loader/src/test/resources/log4j.xml
  brmo-loader/src/test/java/nl/b3p/GH527NhrToStagingToRsgbIntegrationTest.java
  brmo-loader/src/test/java/nl/b3p/NhrToStagingToRsgbIntegrationTest.java
  brmo-loader/src/test/resources/log4j.xml
Labels: Hacktoberfest :beers:, bouw- en testinfrastuctuur
