Repository B3Partners/brmo, pull requests merged in 2018-05, with the labels that each got.

#437 Update kadaster-gds2 (1.2 -> 1.3) dependency
  pom.xml
Labels: bouw- en testinfrastuctuur, enhancement :+1:

#440 gebruik kadaster-gds2 v 1.3 voor hotfix branch 1.5.2.x
  pom.xml
Labels: BRK, brmo-commandline, brmo-service

#442 Update dependencies (oa. GeoTools 19.1) en maven plugins
  pom.xml
Labels: bouw- en testinfrastuctuur, enhancement :+1:

#438 fix translatie fout nHR bericht
  brmo-loader/src/main/resources/xsl/nhr-object-ref-2.5.xsl
  brmo-loader/src/main/resources/xsl/nhr-split-2.5.xsl
  brmo-loader/src/main/resources/xsl/nhr-to-rsgb-xml-2.5.xsl
  brmo-loader/src/test/java/nl/b3p/NhrToStagingToRsgbIntegrationTest.java
  brmo-loader/src/test/resources/mantis10752/52019667.xml
  brmo-test-util/src/main/java/nl/b3p/brmo/test/util/database/dbunit/CleanUtil.java
Labels: NHR, bug :bomb:

#439 Duplicaat GDS2 berichten afvangen
  brmo-service/src/main/java/nl/b3p/brmo/service/scanner/GDS2OphalenProces.java
Labels: BRK, brmo-service, enhancement :+1:
