Repository B3Partners/brmo, pull requests merged in 2019-11, with the labels that each got.

#720 Defaulthandler toegevoegd voor als transformatie is afgelopen
  brmo-service/src/main/java/nl/b3p/brmo/service/stripes/TransformActionBean.java
Labels: brmo-service, functie wens :+1:

#719 Added index. Use correct cast to prevent sequential scanning
  datamodel/datamodel.xsl
  datamodel/extra_scripts/oracle/122_idx_gebr_doel.sql
  datamodel/extra_scripts/oracle/207_brk_views.sql
  datamodel/extra_scripts/postgresql/122_idx_gebr_doel.sql
  datamodel/extra_scripts/postgresql/207_brk_views.sql
  datamodel/extra_scripts/sqlserver/122_idx_gebr_doel.sql
  datamodel/extra_scripts/sqlserver/207_brk_views.sql
  datamodel/upgrade_scripts/1.6.3-1.6.4/oracle/rsgb.sql
  datamodel/upgrade_scripts/1.6.3-1.6.4/postgresql/rsgb.sql
  datamodel/upgrade_scripts/1.6.3-1.6.4/sqlserver/rsgb.sql
Labels: bug :bomb:

#727 voeg een lock om de build loop heen zodat er maar 1 brmo build tegelijk kan draaien
  Jenkinsfile
Labels: bouw- en testinfrastuctuur

#726 voeg de optie "ON OVERFLOW TRUNCATE WITH COUNT" toe aan de ORACLE LISTAGG calls
  datamodel/extra_scripts/oracle/207_brk_views.sql
Labels: bug :bomb:, oracle, rsgb

#733 1.6.4-SNAPSHOT wordt 2.0.0-SNAPSHOT
  .gitignore
  .jenkins/execute-upgrade-extras-oracle.sh
  .jenkins/execute-upgrades-oracle.sh
  .travis.yml
  .travis/execute-upgrade-extras-pgsql.sh
  .travis/execute-upgrades-pgsql.sh
  .travis/getlastRelease.sh
  appveyor.yml
  bgt-gml-loader/pom.xml
  brmo-commandline/pom.xml
  brmo-dist/pom.xml
  brmo-init-util/pom.xml
  brmo-loader/pom.xml
  brmo-persistence/pom.xml
  brmo-proxyservice/pom.xml
  brmo-service/pom.xml
  brmo-soap-util/pom.xml
  brmo-soap/pom.xml
  brmo-stufbg204/pom.xml
  brmo-taglib/pom.xml
  brmo-test-util/pom.xml
  datamodel/extra_scripts/sqlserver/50_zak_recht_archief.sql
  datamodel/pom.xml
  datamodel/upgrade_scripts/1.6.3-2.0.0/oracle/rsgb.sql
  datamodel/upgrade_scripts/1.6.3-2.0.0/oracle/rsgbbgt.sql
  datamodel/upgrade_scripts/1.6.3-2.0.0/oracle/staging.sql
  datamodel/upgrade_scripts/1.6.3-2.0.0/postgresql/rsgb.sql
  datamodel/upgrade_scripts/1.6.3-2.0.0/postgresql/rsgbbgt.sql
  datamodel/upgrade_scripts/1.6.3-2.0.0/postgresql/staging.sql
  datamodel/upgrade_scripts/1.6.3-2.0.0/sqlserver/rsgb.sql
  datamodel/upgrade_scripts/1.6.3-2.0.0/sqlserver/rsgbbgt.sql
  datamodel/upgrade_scripts/1.6.3-2.0.0/sqlserver/staging.sql
  pom.xml
  topparser/pom.xml
Labels: bouw- en testinfrastuctuur

#732 Travis-CI build matrix update
  .travis.yml
  .travis/settings.xml
Labels: bouw- en testinfrastuctuur

#711 P8 integratie tests van datamodel
  .gitignore
  .jenkins/drop-rsgb-views.sql
  .travis/drop-rsgb-views-pgsql.sql
  .travis/refresh-rsgb-mviews-pgsql.sql
  .travis/reinstall-rsgb-views-pgsql.sh
  Jenkinsfile
  brmo-test-util/pom.xml
  brmo-test-util/src/main/java/nl/b3p/brmo/test/util/database/ViewUtils.java
  datamodel/pom.xml
  datamodel/src/test/java/nl/b3p/brmo/datamodel/P8RestAPIIntegrationTest.java
  datamodel/src/test/java/nl/b3p/brmo/datamodel/P8ServicesIntegrationTest.java
  datamodel/src/test/java/nl/b3p/brmo/datamodel/P8TestFramework.java
  datamodel/src/test/resources/P8.properties
  datamodel/src/test/resources/log4j.xml
  pom.xml
Labels: Hacktoberfest :beers:, datamodel, postgres, rsgb, taak

#738 Bump geotools 22.0 -> 22.1
  pom.xml
Labels: dependency update

#742 cleanup CI build / test matrices
  .travis.yml
  Jenkinsfile
  appveyor.yml
Labels: bouw- en testinfrastuctuur

#747 [oracle] Geef de `grootte_perceel` kolom expliciet een naam
  datamodel/extra_scripts/oracle/207_brk_views.sql
  datamodel/upgrade_scripts/2.0.0-2.0.1/oracle/rsgb.sql
Labels: bug :bomb:, oracle, rsgb

#748 Voeg een kolom 'ingangsdatum_recht' toe aan de views
  datamodel/extra_scripts/oracle/207_brk_views.sql
  datamodel/extra_scripts/postgresql/207_brk_views.sql
  datamodel/extra_scripts/sqlserver/207_brk_views.sql
  datamodel/upgrade_scripts/2.0.0-2.0.1/oracle/rsgb.sql
  datamodel/upgrade_scripts/2.0.0-2.0.1/postgresql/rsgb.sql
  datamodel/upgrade_scripts/2.0.0-2.0.1/sqlserver/rsgb.sql
Labels: functie wens :+1:, rsgb
