Repository B3Partners/brmo, pull requests merged in 2019-10, with the labels that each got.

#701 fix NPE in Mantis6235IntegrationTest
  brmo-loader/src/main/resources/xsl/brk-snapshot-to-rsgb-xml.xsl
  brmo-loader/src/test/java/nl/b3p/Mantis6235IntegrationTest.java
  brmo-loader/src/test/resources/mantis6235/staging.xml
Labels: BRK, Hacktoberfest :beers:, bug :bomb:

#704 probeer alleen de voor de transformatie benodigde datasources te openen
  brmo-service/src/main/java/nl/b3p/brmo/service/scanner/LaadprocesTransformatieUitvoeren.java
  brmo-service/src/main/webapp/WEB-INF/jsp/laadproces/list.jsp
Labels: Hacktoberfest :beers:, functie wens :+1:

#568 upgrade GDS2 module voor v20170401
  brmo-loader/src/main/java/nl/b3p/brmo/loader/BrmoFramework.java
  brmo-loader/src/main/java/nl/b3p/brmo/loader/StagingProxy.java
  brmo-loader/src/main/java/nl/b3p/brmo/loader/entity/LaadProces.java
  brmo-loader/src/main/java/nl/b3p/brmo/loader/util/StagingRowHandler.java
  brmo-persistence/db/brmo-persistence-h2.sql
  brmo-persistence/db/create-brmo-persistence-oracle.sql
  brmo-persistence/db/create-brmo-persistence-postgresql.sql
  brmo-persistence/db/create-brmo-persistence-sqlserver.sql
  brmo-persistence/src/main/java/nl/b3p/brmo/persistence/staging/LaadProces.java
  brmo-service/pom.xml
  brmo-service/src/main/java/nl/b3p/brmo/service/scanner/GDS2OphalenProces.java
  brmo-service/src/main/java/nl/b3p/brmo/service/stripes/LaadProcesActionBean.java
  brmo-service/src/main/webapp/WEB-INF/classes/log4j.properties
  brmo-service/src/main/webapp/WEB-INF/jsp/beheer/editgds2proces.jsp
  brmo-service/src/main/webapp/scripts/laadprocessen.js
  brmo-soap-util/src/main/java/nl/b3p/brmo/soap/util/LogMessageHandler.java
  datamodel/upgrade_scripts/1.6.3-1.6.4/oracle/staging.sql
  datamodel/upgrade_scripts/1.6.3-1.6.4/postgresql/staging.sql
  datamodel/upgrade_scripts/1.6.3-1.6.4/sqlserver/staging.sql
  pom.xml
Labels: brmo-service, functie wens :+1:, staging

#709 Bump jdbc-util 3.0 -> 4.0
  pom.xml
Labels: Hacktoberfest :beers:, dependency update

#708 Codecov en andere CI updates
  .travis.yml
  Jenkinsfile
  README.md
  appveyor.yml
  brmo-loader/pom.xml
  brmo-test-util/pom.xml
  codecov.yml
  pom.xml
  topparser/pom.xml
Labels: Hacktoberfest :beers:, bouw- en testinfrastuctuur

#713 testen tegen mssql 2019
  .travis.yml
  .travis/install-mssql2019.sh
Labels: bouw- en testinfrastuctuur

#617 versie 2.1 van de views
  .jenkins/db-prepare-rsgb.sh
  .jenkins/db-prepare-rsgbbgt.sh
  .jenkins/db-prepare-staging.sh
  .jenkins/db-prepare-topnl.sh
  .jenkins/execute-upgrade-extras-oracle.sh
  .jenkins/execute-upgrades-oracle.sh
  .jenkins/login.sql
  .jenkins/setup-old.sh
  .travis.yml
  .travis/execute-upgrade-extras-pgsql.sh
  .travis/install-mssql2019.sh
  Jenkinsfile
  appveyor.yml
  brmo-loader/src/main/resources/xsl/brk-snapshot-to-rsgb-xml.xsl
  brmo-loader/src/test/java/nl/b3p/Mantis6235IntegrationTest.java
  brmo-loader/src/test/resources/mantis6235/staging.xml
  brmo-soap/pom.xml
  brmo-soap/src/main/java/nl/b3p/brmo/soap/db/EigendomInfo.java
  brmo-soap/src/test/java/nl/b3p/brmo/soap/db/EigendomInfoIntegrationTest.java
  brmo-soap/src/test/java/nl/b3p/brmo/soap/db/TestUtil.java
  datamodel/extra_scripts/oracle/206_bag_views.sql
  datamodel/extra_scripts/oracle/207_brk_views.sql
  datamodel/extra_scripts/postgresql/206_bag_views.sql
  datamodel/extra_scripts/postgresql/207_brk_views.sql
  datamodel/extra_scripts/sqlserver/206_bag_views.sql
  datamodel/extra_scripts/sqlserver/207_brk_views.sql
  datamodel/upgrade_scripts/1.6.3-1.6.4/oracle/rsgb.sql
  datamodel/upgrade_scripts/1.6.3-1.6.4/postgresql/rsgb.sql
  datamodel/upgrade_scripts/1.6.3-1.6.4/sqlserver/rsgb.sql
Labels: functie wens :+1:

#714 vervang dubbele spatie in samengestelde naam met een enkele spatie
  datamodel/extra_scripts/oracle/207_brk_views.sql
  datamodel/extra_scripts/postgresql/207_brk_views.sql
  datamodel/extra_scripts/sqlserver/207_brk_views.sql
Labels: Hacktoberfest :beers:, bug :bomb:, rsgb

#715 Voeg een db_xml bijwerken optie toe aan update proces
  brmo-loader/src/main/java/nl/b3p/brmo/loader/RsgbProxy.java
  brmo-loader/src/main/java/nl/b3p/brmo/loader/entity/Bericht.java
  brmo-loader/src/main/java/nl/b3p/brmo/loader/updates/UpdateProcess.java
  brmo-loader/src/main/java/nl/b3p/brmo/loader/util/TableData.java
  brmo-service/src/main/java/nl/b3p/brmo/service/stripes/UpdatesActionBean.java
  brmo-service/src/test/java/nl/b3p/brmo/service/stripes/AdvancedFunctionsAfterAddingBeginDateActionBeanIntegrationTest.java
  brmo-service/src/test/java/nl/b3p/brmo/service/stripes/UpdateBeginDatumZakRechtIntegrationTest.java
Labels: Hacktoberfest :beers:, functie wens :+1:

#718 dependabot config
  .dependabot/config.yml
Labels: bouw- en testinfrastuctuur
