Repository B3Partners/brmo, pull requests merged in 2021-11, with the labels that each got.

#1203 Update build matrix
  .github/workflows/linux-mssql.yml
  .github/workflows/linux.yml
  appveyor.yml
Labels: bouw- en testinfrastuctuur

#1204 No concurrent integration tests for bgt-loader
  .github/workflows/linux-mssql.yml
  .github/workflows/linux-oracle.yml
  .github/workflows/linux.yml
  .github/workflows/windows-sqlserver.yml
Labels: bouw- en testinfrastuctuur

#1206 Oracle XE docker image update
  .build/ci/oracle-start-docker.sh
  .build/ci/oracle/github.connections.brmo-persistence.properties
  .build/ci/oracle/github.oracle.brmo-commandline.properties
  .build/ci/oracle/github.oracle.brmo-loader.properties
  .build/ci/oracle/github.oracle.brmo-service.properties
  .build/ci/oracle/github.oracle.brmo-soap.properties
  .build/ci/oracle/github.oracle.brmo-stufbg204.properties
  .build/ci/oracle/github.oracle.datamodel.properties
  .github/workflows/linux-mssql.yml
  .github/workflows/linux-oracle.yml
  .github/workflows/linux.yml
  .github/workflows/upgrade-oracle.yml
  .github/workflows/upgrade-pgsql.yml
  bgt-loader/README.md
  bgt-loader/pom.xml
Labels: Oracle, bouw- en testinfrastuctuur

#1212 Bump GeoTools 26.0 -> 26.1 en jdbc-util ook
  .github/dependabot.yml
  pom.xml
Labels: dependency update

#1214 Bump jakarta.mail.version 1.6.6 -> 1.6.7
  pom.xml
Labels: dependency update

#1216 [BRMO-124] [BRMO-125] Improve loading of BAG2 extracts
  bag2-loader/src/main/java/nl/b3p/brmo/bag2/loader/BAG2Database.java
  bag2-loader/src/main/java/nl/b3p/brmo/bag2/loader/BAG2LoaderUtils.java
  bag2-loader/src/main/java/nl/b3p/brmo/bag2/loader/cli/BAG2LoaderMain.java
  bag2-loader/src/test/java/nl/b3p/brmo/bag2/loader/BAG2LoaderUtilsTest.java
  brmo-service/src/main/java/nl/b3p/brmo/service/stripes/BAG2LoadActionBean.java
Labels: BAG, bag2-loader

#1221 Upgrade scripts voor 2.2.0
  .build/ci/getlastRelease.sh
  .build/ci/oracle-execute-upgrades.sh
  .build/ci/pgsql-execute-upgrades.sh
  .jenkins/execute-upgrades-oracle.sh
  datamodel/src/test/java/nl/b3p/brmo/datamodel/DatabaseUpgradeTest.java
  datamodel/upgrade_scripts/2.1.0-2.2.0/oracle/rsgb.sql
  datamodel/upgrade_scripts/2.1.0-2.2.0/oracle/rsgbbgt.sql
  datamodel/upgrade_scripts/2.1.0-2.2.0/oracle/staging.sql
  datamodel/upgrade_scripts/2.1.0-2.2.0/postgresql/rsgb.sql
  datamodel/upgrade_scripts/2.1.0-2.2.0/postgresql/rsgbbgt.sql
  datamodel/upgrade_scripts/2.1.0-2.2.0/postgresql/staging.sql
  datamodel/upgrade_scripts/2.1.0-2.2.0/sqlserver/rsgb.sql
  datamodel/upgrade_scripts/2.1.0-2.2.0/sqlserver/rsgbbgt.sql
  datamodel/upgrade_scripts/2.1.0-2.2.0/sqlserver/staging.sql
Labels: bouw- en testinfrastuctuur

#1219 [BRMO-99] BAG 2.0 Standaard views
  brmo-dist/assembly.xml
  datamodel/extra_scripts/oracle/208_bag2_views.sql
  datamodel/extra_scripts/postgresql/208_bag2_views.sql
Labels: functie wens, BAG

#1225 Bump junit-bom from 5.8.1 to 5.8.2
  pom.xml
Labels: bouw- en testinfrastuctuur, dependency update

#1224 Update upgrade script generator
  .build/ci/getlastRelease.sh
  .build/ci/oracle-execute-upgrades.sh
  .build/ci/pgsql-execute-upgrades.sh
  .jenkins/execute-upgrades-oracle.sh
  appveyor.yml
  datamodel/src/test/java/nl/b3p/brmo/datamodel/DatabaseUpgradeTest.java
  datamodel/upgrade_scripts/2.2.0-2.2.1/oracle/rsgbbgt.sql
  datamodel/upgrade_scripts/2.2.0-2.2.1/postgresql/rsgbbgt.sql
  datamodel/upgrade_scripts/2.2.0-2.2.1/sqlserver/rsgbbgt.sql
  datamodel/upgrade_scripts/new-version-upgrades.sh
  docker/src/main/docker/Dockerfile
Labels: bouw- en testinfrastuctuur
