Repository B3Partners/brmo, pull requests merged in 2022-02, with the labels that each got.

#1279 Bump mssql-jdbc van 9.4.1.jre11 naar 10.2.0.jre11
  .github/dependabot.yml
  bgt-loader/README.md
  bgt-loader/pom.xml
  bgt-loader/src/main/resources/BGTLoader.properties
  brmo-commandline/src/test/resources/mssql.properties
  brmo-loader/src/test/resources/sqlserver.properties
  brmo-persistence/src/test/resources/connections.properties
  brmo-service/src/test/resources/sqlserver.properties
  brmo-soap/src/test/resources/sqlserver.properties
  brmo-stufbg204/src/test/resources/sqlserver.properties
  brmo-test-util/src/test/java/nl/b3p/brmo/test/util/database/dbunit/DBUnitExportRSGB.java
  datamodel/src/test/resources/sqlserver.properties
  pom.xml
Labels: MS SQL Server, dependency update

#1284 Use logger instead of System.err directly
  bgt-loader/src/main/java/nl/b3p/brmo/bgt/loader/cli/BGTLoaderMain.java
  bgt-loader/src/main/java/nl/b3p/brmo/bgt/loader/cli/DownloadCommand.java
  bgt-loader/src/main/resources/bgt-loader-cli-log4.properties
Labels: bug

#1285 Check for metadata value whether to do initial load or update
  brmo-service/src/main/java/nl/b3p/brmo/service/scanner/BGTLoader.java
Labels: bug

#1286 Allow BAG and BGT processes to run after last run exited with ERROR status
  brmo-service/src/main/java/nl/b3p/brmo/service/scanner/BAG2MutatieProcesRunner.java
  brmo-service/src/main/java/nl/b3p/brmo/service/scanner/BGTLoader.java
Labels: bug

#1290 Change update scripts to modify brmo_metadata.waarde column type to clob for BGT
  datamodel/upgrade_scripts/2.2.0-2.2.1/oracle/rsgbbgt.sql
  datamodel/upgrade_scripts/2.2.0-2.2.1/postgresql/rsgbbgt.sql
  datamodel/upgrade_scripts/2.2.0-2.2.1/sqlserver/rsgbbgt.sql
Labels: bug, datamodel, Oracle, PostgreSQL, MS SQL Server, BGT, rsgbbgt, bgt-loader

#1291 opruimen van release candidate upgrade scripts
  datamodel/upgrade_scripts/2.0.3-2.1.0-rc1/oracle/rsgb.sql
  datamodel/upgrade_scripts/2.0.3-2.1.0-rc1/postgresql/rsgb.sql
  datamodel/upgrade_scripts/2.0.3-2.1.0-rc1/sqlserver/rsgb.sql
  datamodel/upgrade_scripts/2.1.0-2.2.0-rc1/oracle/rsgb.sql
  datamodel/upgrade_scripts/2.1.0-2.2.0-rc1/oracle/rsgbbgt.sql
  datamodel/upgrade_scripts/2.1.0-2.2.0-rc1/oracle/staging.sql
  datamodel/upgrade_scripts/2.1.0-2.2.0-rc1/postgresql/rsgb.sql
  datamodel/upgrade_scripts/2.1.0-2.2.0-rc1/postgresql/rsgbbgt.sql
  datamodel/upgrade_scripts/2.1.0-2.2.0-rc1/postgresql/staging.sql
  datamodel/upgrade_scripts/2.1.0-2.2.0-rc1/sqlserver/rsgb.sql
  datamodel/upgrade_scripts/2.1.0-2.2.0-rc1/sqlserver/rsgbbgt.sql
  datamodel/upgrade_scripts/2.1.0-2.2.0-rc1/sqlserver/staging.sql
Labels: bouw- en testinfrastuctuur

#1298 Test BAG 2 schema upgrades
  .build/ci/oracle-execute-upgrades.sh
  .build/ci/oracle/github.oracle.datamodel.properties
  .build/ci/pgsql-execute-upgrades.sh
  .github/workflows/upgrade-oracle.yml
  .github/workflows/upgrade-pgsql.yml
  Jenkinsfile
  datamodel/src/test/java/nl/b3p/brmo/datamodel/DatabaseUpgradeTest.java
  datamodel/src/test/resources/oracle.properties
  datamodel/src/test/resources/postgis.properties
  datamodel/upgrade_scripts/2.2.0-2.2.1/oracle/bag.sql
  datamodel/upgrade_scripts/2.2.0-2.2.1/oracle/rsgbbgt.sql
  datamodel/upgrade_scripts/2.2.0-2.2.1/postgresql/bag.sql
  datamodel/upgrade_scripts/new-version-upgrades.sh
Labels: bouw- en testinfrastuctuur

#1303 fix upgrade scripts voor 2.2.2
  .build/ci/pgsql-execute-upgrades.sh
  datamodel/src/test/java/nl/b3p/brmo/datamodel/DatabaseUpgradeTest.java
  datamodel/upgrade_scripts/2.2.0-2.2.1/postgresql/bag.sql
  datamodel/upgrade_scripts/2.2.1-2.2.2/oracle/bag.sql
  datamodel/upgrade_scripts/2.2.1-2.2.2/oracle/rsgbbgt.sql
  datamodel/upgrade_scripts/2.2.1-2.2.2/postgresql/bag.sql
  datamodel/upgrade_scripts/2.2.1-2.2.2/postgresql/rsgbbgt.sql
  datamodel/upgrade_scripts/2.2.1-2.2.2/sqlserver/bag.sql
  datamodel/upgrade_scripts/2.2.1-2.2.2/sqlserver/rsgbbgt.sql
  datamodel/upgrade_scripts/new-version-upgrades.sh
Labels: Oracle, PostgreSQL, MS SQL Server, bouw- en testinfrastuctuur

#1304 [SUPPORT-12989] Hou `com.sun.mail:jakarta.mail` en `com.sun.activation:jakarta.activation` uit de war file
  pom.xml
Labels: regressie, brmo-service

#1315 Gebruik PostGIS Alpine docker images
  .github/workflows/linux.yml
Labels: bouw- en testinfrastuctuur

#1320 Bump geotools.version 26.2 ➜ 26.3 en jdbc-util.version 11.1 ➜ 11.2
  pom.xml
Labels: dependency update
