Repository B3Partners/brmo, pull requests merged in 2022-12, with the labels that each got.

#1607 Drop Oracle 18.4.0 ondersteuning; die is inmiddels EOL
  .github/workflows/linux-oracle.yml
  .github/workflows/upgrade-oracle.yml
  .jenkins/start-oracle-brmo.sh
  bag2-loader/README.md
  bgt-loader/README.md
Labels: Oracle, bouw- en testinfrastuctuur

#1610 fix brk / 3.0.0 upgrade scripts
  .build/ci/oracle-execute-upgrades.sh
  .build/ci/pgsql-execute-upgrades.sh
  .jenkins/execute-upgrades-oracle.sh
  .mvn/owasp-suppression.xml
  pom.xml
Labels: BRK, bouw- en testinfrastuctuur

#1119 Use GeoTools gml-geometry-streaming module in DataComfortXMLReader
  brmo-loader/pom.xml
  brmo-loader/src/main/java/nl/b3p/brmo/loader/util/DataComfortXMLReader.java
  brmo-loader/src/test/java/nl/b3p/brmo/loader/entity/BagBerichtIntegrationTest.java
  brmo-loader/src/test/java/nl/b3p/brmo/loader/util/DataComfortXMLReaderTest.java
  brmo-loader/src/test/resources/nl/b3p/brmo/loader/util/comfortdata32.xml
Labels: functie wens, BRK

#1621 Bye-bye LGTM
  .lgtm/settings.xml
  README.md
  bag2-loader/pom.xml
  bgt-loader/pom.xml
  bgt-loader/src/main/java/nl/b3p/brmo/util/http/HttpSeekableByteChannel.java
  docker/pom.xml
  lgtm.yml
Labels: bouw- en testinfrastuctuur
