Repository B3Partners/brmo, pull requests merged in 2022-04, with the labels that each got.

#1371 Add rsgbbag JNDI resource voor docker image
  docker/src/main/docker/tomcat_conf/server.xml
Labels: bouw- en testinfrastuctuur

#1377 Bump geotools.version 26.3 ➜ 26.4
  .mvn/owasp-suppression.xml
  pom.xml
Labels: dependency update

#1372 Parse BAG2 leveringsdocument instead of relying on filename
  bag2-loader/.reuse/dep5
  bag2-loader/README.md
  bag2-loader/pom.xml
  bag2-loader/src/main/java/nl/b3p/brmo/bag2/loader/BAG2LoaderUtils.java
  bag2-loader/src/main/java/nl/b3p/brmo/bag2/loader/cli/BAG2LoaderMain.java
  bag2-loader/src/main/java/nl/b3p/brmo/bag2/loader/cli/BAG2MutatiesCommand.java
  bag2-loader/src/main/resources/BAG2Loader.properties
  bag2-loader/src/main/resources/BAG2Loader_nl.properties
  bag2-loader/src/main/xsd/lvbag-extract-v20200601/extract-levering/v20200601/BagvsExtractLeveringsdocument-2.1.0.xsd
  bag2-loader/src/main/xsd/lvbag-extract-v20200601/extract-selecties/v20200601/BagvsExtractSelecties-2.1.0.xsd
  bag2-loader/src/test/java/nl/b3p/brmo/bag2/loader/BAG2LoaderUtilsTest.java
  pom.xml
Labels: bug, functie wens, BAG, bag2-loader

#1380 BAG 2.0: Do not show an exception when brmo_metadata table does not exist
  brmo-service/src/main/java/nl/b3p/brmo/service/stripes/BAG2LoadActionBean.java
Labels: bug

#1383 Migratie bestanden aanmaken voor upgrade 2.2.2-2.3.0
  .build/ci/getlastRelease.sh
  .build/ci/oracle-execute-upgrades.sh
  .build/ci/pgsql-execute-upgrades.sh
  .jenkins/execute-upgrades-oracle.sh
  datamodel/src/test/java/nl/b3p/brmo/datamodel/DatabaseUpgradeTest.java
  datamodel/src/test/java/nl/b3p/brmo/datamodel/P8RestAPIIntegrationTest.java
  datamodel/src/test/java/nl/b3p/brmo/datamodel/P8ServicesIntegrationTest.java
  datamodel/upgrade_scripts/2.2.2-2.3.0/oracle/bag.sql
  datamodel/upgrade_scripts/2.2.2-2.3.0/oracle/rsgb.sql
  datamodel/upgrade_scripts/2.2.2-2.3.0/oracle/rsgbbgt.sql
  datamodel/upgrade_scripts/2.2.2-2.3.0/oracle/staging.sql
  datamodel/upgrade_scripts/2.2.2-2.3.0/postgresql/bag.sql
  datamodel/upgrade_scripts/2.2.2-2.3.0/postgresql/rsgb.sql
  datamodel/upgrade_scripts/2.2.2-2.3.0/postgresql/rsgbbgt.sql
  datamodel/upgrade_scripts/2.2.2-2.3.0/postgresql/staging.sql
  datamodel/upgrade_scripts/new-version-upgrades.sh
  docker/src/main/docker/Dockerfile
  docker/src/main/docker/pg_conf/Dockerfile
  src/site/markdown/developer-notes.md
Labels: bouw- en testinfrastuctuur
