Repository B3Partners/brmo, pull requests merged in 2022-05, with the labels that each got.

#1323 Initiele NHR lader
  .github/workflows/linux-oracle.yml
  .github/workflows/linux.yml
  brmo-persistence/db/create-brmo-persistence-oracle.sql
  brmo-persistence/db/create-brmo-persistence-postgresql.sql
  brmo-persistence/db/drop-brmo-persistence-oracle.sql
  brmo-persistence/db/drop-brmo-persistence-postgresql.sql
  brmo-persistence/src/main/java/nl/b3p/brmo/persistence/staging/NHRInschrijving.java
  brmo-persistence/src/main/resources/META-INF/orm-oracle.xml
  brmo-persistence/src/main/resources/META-INF/persistence.xml
  brmo-service/pom.xml
  brmo-service/src/main/java/nl/b3p/brmo/service/jobs/GeplandeTakenContextListener.java
  brmo-service/src/main/java/nl/b3p/brmo/service/jobs/GeplandeTakenInit.java
  brmo-service/src/main/java/nl/b3p/brmo/service/jobs/NHRJob.java
  brmo-service/src/main/java/nl/b3p/brmo/service/scanner/GDS2OphalenProces.java
  brmo-service/src/main/java/nl/b3p/brmo/service/stripes/NHRActionBean.java
  brmo-service/src/main/webapp/META-INF/context.xml
  brmo-service/src/main/webapp/WEB-INF/classes/log4j.properties
  brmo-service/src/main/webapp/WEB-INF/jsp/bestand/form.jsp
  brmo-service/src/main/webapp/WEB-INF/jsp/nhr/list.jsp
  brmo-service/src/main/webapp/scripts/nhr.js
  brmo-soap-util/pom.xml
  datamodel/upgrade_scripts/2.2.2-2.3.0/oracle/staging.sql
  datamodel/upgrade_scripts/2.2.2-2.3.0/postgresql/staging.sql
  nhr-loader/LICENSES/CC0-1.0.txt
  nhr-loader/LICENSES/MIT.txt
  nhr-loader/pom.xml
  nhr-loader/src/main/java/nl/b3p/brmo/nhr/loader/NHRCertificateOptions.java
  nhr-loader/src/main/java/nl/b3p/brmo/nhr/loader/NHRDatabaseOptions.java
  nhr-loader/src/main/java/nl/b3p/brmo/nhr/loader/NHRLoader.java
  nhr-loader/src/main/java/nl/b3p/brmo/nhr/loader/NHRLoaderUtils.java
  nhr-loader/src/main/java/nl/b3p/brmo/nhr/loader/cli/NHRLoadOptions.java
  nhr-loader/src/main/java/nl/b3p/brmo/nhr/loader/cli/NHRLoadUtils.java
  nhr-loader/src/main/java/nl/b3p/brmo/nhr/loader/cli/NHRLoaderMain.java
  nhr-loader/src/main/resources/NHRLoader.properties
  nhr-loader/src/main/resources/NHRLoader_nl.properties
  nhr-loader/src/main/resources/nhr-loader-cli-log4j.properties
  nhr-loader/src/wsdl/KVK-KvKDataservice.wsdl
  pom.xml
Labels: NHR

#1404 [BRMO-180] Gebruik relatie SplitsingAfkoopErfpacht in `vb_util_app_re_splitsing`
  datamodel/extra_scripts/oracle/207_brk_views.sql
  datamodel/extra_scripts/postgresql/207_brk_views.sql
  datamodel/upgrade_scripts/2.2.2-2.3.0/oracle/rsgb.sql
  datamodel/upgrade_scripts/2.2.2-2.3.0/postgresql/rsgb.sql
Labels: bug

#1403 vervang org.codehaus.mojo:jaxb2-maven-plugin door org.jvnet.jaxb2.maven2:maven-jaxb2-plugin
  bag2-loader/pom.xml
  pom.xml
Labels: bouw- en testinfrastuctuur

#1412 nhr-loader: manually exclude javamail transitive dependency
  nhr-loader/pom.xml
Labels: bug

#1414 brmo-service: add email reading support
  brmo-service/src/main/java/nl/b3p/brmo/service/jobs/GeplandeTakenInit.java
  brmo-service/src/main/java/nl/b3p/brmo/service/jobs/NHREmailJob.java
  brmo-service/src/main/webapp/META-INF/context.xml
Labels: functie wens

#1425 nhr-loader: support not providing alias
  brmo-service/src/main/java/nl/b3p/brmo/service/jobs/NHRJob.java
  brmo-service/src/main/java/nl/b3p/brmo/service/stripes/NHRActionBean.java
  nhr-loader/src/main/java/nl/b3p/brmo/nhr/loader/cli/NHRLoadUtils.java
Labels: bug, NHR

#1426 brmo-service: allow uploading CSVs for NHR
  brmo-service/src/main/java/nl/b3p/brmo/service/stripes/NHRActionBean.java
Labels: NHR
