Repository B3Partners/brmo, pull requests merged in 2023-02, with the labels that each got.

#1690 Add Trivy scanner for docker images
  .github/workflows/trivy.yml
Labels: bouw- en testinfrastuctuur

#1689 [BRMO-258] Genereer database schema documentatie voor brk (en bag) schema's naast public/rsgb schema
  brmo-test-util/src/main/java/nl/b3p/brmo/test/util/database/dbunit/CleanUtil.java
  datamodel/brk/brk2.0_commentaar.sql
  datamodel/brk/brk2.0_oracle_views.sql
  datamodel/brk/brk2.0_postgresql_views.sql
  datamodel/extra_scripts/postgresql/208_bag2_views.sql
  datamodel/extra_scripts/postgresql/209_bag2_rsgb_views.sql
  datamodel/pom.xml
  datamodel/src/site/site.xml
  datamodel/src/test/resources/pgsql.properties
  pom.xml
  src/site/markdown/developer-notes.md
Labels: functie wens

#1695 cleanup stale PR
  .github/workflows/cleanup_and_maintainance.yml
Labels: bouw- en testinfrastuctuur

#1696 Gebruik een typed query
  brmo-service/src/main/java/nl/b3p/brmo/service/stripes/OphaalConfigActionBean.java
Labels: bug

#1697 Fix "Unsafe use of getResource" security meldingen
  .github/workflows/codeql-analysis.yml
  brmo-loader/src/main/java/nl/b3p/brmo/loader/util/RsgbTransformer.java
  brmo-loader/src/main/java/nl/b3p/brmo/loader/xml/BRPXMLReader.java
  brmo-loader/src/main/java/nl/b3p/brmo/loader/xml/NhrXMLReader.java
  brmo-loader/src/main/java/nl/b3p/brmo/loader/xml/WozXMLReader.java
Labels: bug

#1694 [SUPPORT-13459] fix `vb_verblijfsobject_adres` voor Oracle
  datamodel/extra_scripts/oracle/208_bag2_views.sql
Labels: BAG, Oracle

#1698 [BRMO-270] Gebruik geen archief tabel voor onroerendezaakfiliatie
  brmo-loader/src/main/java/nl/b3p/brmo/loader/xml/NhrXMLReader.java
  brmo-loader/src/main/resources/xsl/brk2-snapshot-to-rsgb-xml.xsl
  brmo-loader/src/test/java/nl/b3p/Brk2MutatieVerwijderVerwerkingIntegrationTest.java
  brmo-loader/src/test/java/nl/b3p/Brk2StandMutatieGedeeldeStukkenVerwerkingIntegrationTest.java
  brmo-loader/src/test/java/nl/b3p/Brk2StandMutatieVerwerkingIntegrationTest.java
  brmo-test-util/src/main/java/nl/b3p/brmo/test/util/database/dbunit/CleanUtil.java
  datamodel/brk/brk2.0_commentaar.sql
  datamodel/brk/brk2.0_oracle.sql
  datamodel/brk/brk2.0_oracle_views.sql
  datamodel/brk/brk2.0_postgresql.sql
  datamodel/brk/brk2.0_postgresql_views.sql
  datamodel/brk/delete-brk2.0_oracle.sql
  datamodel/brk/delete-brk2.0_postgresql.sql
Labels: BRK

#1702 [BRMO-252] fix database upgrade test
  .build/ci/oracle-setup-previous.sh
  .build/ci/oracle/github.oracle.datamodel.properties
  .build/ci/pgsql-setup-previous.sh
  .jenkins/setup-old.sh
  datamodel/src/test/java/nl/b3p/brmo/datamodel/BAGViewsTest.java
  datamodel/src/test/java/nl/b3p/brmo/datamodel/DatabaseUpgradeTest.java
  datamodel/src/test/java/nl/b3p/brmo/datamodel/MaterializedViewsTest.java
  datamodel/src/test/java/nl/b3p/brmo/datamodel/P8RestAPIIntegrationTest.java
  datamodel/src/test/java/nl/b3p/brmo/datamodel/P8ServicesIntegrationTest.java
  datamodel/src/test/java/nl/b3p/brmo/datamodel/P8TestFramework.java
  datamodel/src/test/java/nl/b3p/brmo/oracle/OracleDriverTest.java
  datamodel/src/test/resources/oracle.properties
  datamodel/upgrade_scripts/2.3.3-3.0.0/postgresql/brk.sql
  datamodel/upgrade_scripts/3.0.0-3.0.1/postgresql/brk.sql
  datamodel/upgrade_scripts/new-version-upgrades.sh
  pom.xml
Labels: bouw- en testinfrastuctuur

#1703 [BRMO-283] negeer falende P8 tests
  datamodel/pom.xml
  datamodel/src/test/java/nl/b3p/brmo/datamodel/P8RestAPIIntegrationTest.java
  datamodel/src/test/java/nl/b3p/brmo/datamodel/P8ServicesIntegrationTest.java
  pom.xml
Labels: bug, bouw- en testinfrastuctuur

#1710 Voeg release drafter workflow toe
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: bouw- en testinfrastuctuur

#1709 [BRMO-284] Gebruik Alpine Linux bases images voor BAG en BGT loader
  bag2-loader/Dockerfile
  bag2-loader/pom.xml
  bgt-loader/Dockerfile
  bgt-loader/pom.xml
  docker/src/main/docker/Dockerfile
  docker/src/main/docker/pg_conf/Dockerfile
Labels: functie wens

#1716 oplossen van "Comparison of narrow type with wide type in loop condition"
  brmo-loader/src/main/java/nl/b3p/brmo/loader/StagingProxy.java
  brmo-service/src/main/java/nl/b3p/brmo/service/stripes/AdvancedFunctionsActionBean.java
Labels: bug

#1720 [BRMO-287][BRMO-288] Verouderde P8 testcases en procedures opruimen
  .github/workflows/linux-oracle.yml
  .github/workflows/linux.yml
  .github/workflows/windows.yml
  Jenkinsfile
  datamodel/pom.xml
  datamodel/src/test/java/nl/b3p/brmo/datamodel/P8RestAPIIntegrationTest.java
  datamodel/src/test/java/nl/b3p/brmo/datamodel/P8ServicesIntegrationTest.java
  datamodel/src/test/java/nl/b3p/brmo/datamodel/P8TestFramework.java
  datamodel/src/test/resources/P8.properties
Labels: deprecated

#1719 Fix "Inconsistent equals and hashCode"
  bag2-loader/src/main/java/nl/b3p/brmo/bag2/loader/BAG2GMLMutatieGroepStream.java
Labels: bug

#1723 [BRMO-290] Opruimen van Jenkins CI workflows 😢
  .build/ci/oracle-clear-schema.sql
  .build/ci/oracle-drop-brmo-views.sql
  .build/ci/oracle-setup-db-properties.sh
  .build/ci/oracle/github.connections.brmo-persistence.properties
  .build/ci/oracle/github.oracle.brmo-commandline.properties
  .build/ci/oracle/github.oracle.brmo-loader.properties
  .build/ci/oracle/github.oracle.brmo-service.properties
  .build/ci/oracle/github.oracle.brmo-soap.properties
  .build/ci/oracle/github.oracle.brmo-stufbg204.properties
  .build/ci/oracle/github.oracle.datamodel.properties
  .github/workflows/linux-oracle.yml
  .github/workflows/upgrade-oracle.yml
  .jenkins/db-grant-topnl.sql
  .jenkins/db-prepare-brk.sh
  .jenkins/db-prepare-rsgb.sh
  .jenkins/db-prepare-staging.sh
  .jenkins/db-prepare-topnl.sh
  .jenkins/execute-upgrade-extras-oracle.sh
  .jenkins/execute-upgrades-oracle.sh
  .jenkins/login.sql
  .jenkins/setup-old.sh
  .jenkins/start-oracle-brmo.sh
  Jenkinsfile
  bgt-loader/pom.xml
  brmo-commandline/src/test/resources/oracle.properties
  brmo-loader/src/test/resources/oracle.properties
  brmo-persistence/src/test/resources/connections.properties
  brmo-service/src/test/resources/oracle.properties
  brmo-soap/src/test/resources/oracle.properties
  brmo-stufbg204/src/test/resources/oracle.properties
  datamodel/src/test/resources/oracle.properties
Labels: bouw- en testinfrastuctuur

#1721 [BRMO-289] Opruimen verouderde "unsupported" maatwerk SQL procedures
  datamodel/unsupported/drenthe/301_create_pv_views_v0.8_2015-06-10.sql
  datamodel/unsupported/drenthe/303_create_pv_map_infoviews_v0.8_2015-06-10.sql
  datamodel/unsupported/drenthe/P8/p8_kadastraal_perceel.sql
  datamodel/unsupported/drenthe/P8/p8_kadastraal_perceel_aantekeningen.sql
  datamodel/unsupported/drenthe/P8/p8_kadastraal_perceel_overgegaan_in.sql
  datamodel/unsupported/drenthe/P8/p8_kadastraal_perceel_rechten.sql
  datamodel/unsupported/drenthe/P8/p8_subject.sql
  datamodel/unsupported/drenthe/P8/p8_subject_percelen.sql
  datamodel/unsupported/drenthe/P8/readme
  datamodel/unsupported/drenthe/datumfunctie.sql
  datamodel/unsupported/drenthe/readme
  datamodel/unsupported/flevoland/401_flv_insert_spatial_view_metadata.sql
  datamodel/unsupported/flevoland/402_flv_create_geotools_geometrycolumns_metatable.sql
  datamodel/unsupported/flevoland/403_flv_create_geotools_primarykey_metatable.sql
  datamodel/unsupported/flevoland/BRMO_Update_RSGBBGT_V1.3.1_1.4.1.txt
  datamodel/unsupported/flevoland/BRMO_Update_RSGB_V1.3.1_1.4.1.sql
  datamodel/unsupported/flevoland/BRMO_Update_Staging_V1.3.1_1.4.1.sql
  datamodel/unsupported/flevoland/flv_oracle_v_kad_perceel_eigenaar.sql
  datamodel/unsupported/flevoland/flv_v_bd_app_re_bij_perceel
  datamodel/unsupported/flevoland/v_kad_perceel_metgeeom.sql
  datamodel/unsupported/gelderland/P8/p8_kadastraal_perceel.sql
  datamodel/unsupported/gelderland/P8/p8_kadastraal_perceel_aantekeningen.sql
  datamodel/unsupported/gelderland/P8/p8_kadastraal_perceel_overgegaan_in.sql
  datamodel/unsupported/gelderland/P8/p8_kadastraal_perceel_rechten.sql
  datamodel/unsupported/gelderland/P8/p8_subject.sql
  datamodel/unsupported/gelderland/P8/p8_subject_percelen.sql
  datamodel/unsupported/gelderland/P8/pm_p8_kadaster_perceel.sql
  datamodel/unsupported/gelderland/P8/pm_p8_kadaster_perceel_eigenaar.sql
  datamodel/unsupported/gelderland/P8/pv_info_i_koz_zak_recht_sk.sql
  datamodel/unsupported/gelderland/pm_perceel_kadaster_archief.sql
  datamodel/unsupported/gelderland/pm_perceel_kadaster_eigenaar.sql
  datamodel/unsupported/gelderland/readme.txt
  datamodel/unsupported/gouda/401_gda_insert_spatial_view_metadata.sql
  datamodel/unsupported/gouda/402_gda_create_geotools_geometrycolumns_metatable.sql
  datamodel/unsupported/overijssel/301_create_pv_views_v0.8_2015-06-10.sql
  datamodel/unsupported/overijssel/303_create_pv_map_infoviews_v0.8_2015-06-10.sql
  datamodel/unsupported/overijssel/ImkadApi v1.1.pdf
  datamodel/unsupported/overijssel/Koppeling_P8_met_BRK_Kadaster_Doc_BRK_API_v1_0.pdf
  datamodel/unsupported/overijssel/P8/P8_kadastraal_perceel_adres.sql
  datamodel/unsupported/overijssel/P8/p8_kadastraal_perceel.sql
  datamodel/unsupported/overijssel/P8/p8_kadastraal_perceel_aantekeningen.sql
  datamodel/unsupported/overijssel/P8/p8_kadastraal_perceel_overgegaan_in.sql
  datamodel/unsupported/overijssel/P8/p8_kadastraal_perceel_rechten.sql
  datamodel/unsupported/overijssel/P8/p8_subject.sql
  datamodel/unsupported/overijssel/P8/p8_subject_percelen.sql
  datamodel/unsupported/overijssel/README.md
  datamodel/unsupported/overijssel/datumfunctie.sql
  datamodel/unsupported/overijssel/geotools_metadata.sql
  datamodel/unsupported/vlaardingen/401_vld_insert_spatial_view_metadata.sql
  datamodel/unsupported/vlaardingen/402_vld_create_geotools_geometrycolumns_metatable.sql
  datamodel/unsupported/vlaardingen/403_vld_uitbreiding_bag_views.sql
  datamodel/unsupported/vlaardingen/404_vld_uitbreiding_brk_views.sql
  datamodel/unsupported/vru/v_adres.sql
  datamodel/unsupported/zeeland/250_create_mviews.sql
  datamodel/unsupported/zeeland/300_drop_oude_views_v0.8_2015-06-10.sql
  datamodel/unsupported/zeeland/301_create_pv_views_v0.8_2015-06-10.sql
  datamodel/unsupported/zeeland/301a_create_pv_view_comments_v0.1_2015.sql
  datamodel/unsupported/zeeland/302_create_pm_tables_v0.8_2015-06-10.sql
  datamodel/unsupported/zeeland/303_create_pv_map_infoviews_v0.8_2015-06-10.sql
  datamodel/unsupported/zeeland/304_refresh_materialized_views.sql
Labels: vraag of documentatie, datamodel, rsgb

#1726 Bump geotools.version: 28.1 ⇨ 28.2 en jdbc-util.version: 13.2 ⇨ 13.3
  pom.xml
Labels: security, dependency update

#1727 Bump jaxws-rt en jaxb-runtime versies
  .mvn/owasp-suppression.xml
  pom.xml
Labels: dependency update
