Repository B3Partners/brmo, pull requests merged in 2024-01, with the labels that each got.

#2006 gebruik unieke naam voor sarif artifact upload
  .github/workflows/codeql-analysis.yml
  .github/workflows/trivy.yml
Labels: bouw- en testinfrastuctuur

#2007 [SUPPORT-14096] Fix Nieuwe PKIoverheid certificaten worden niet vertrouwd door Apache CXF
  brmo-service/src/main/java/nl/b3p/brmo/service/scanner/GDS2OphalenProces.java
  pom.xml
Labels: bug, BRK, regressie, brmo-service, dependency update

#2022 [BRMO-347] Aanpassen connection pool instellingen om ApplicationName toe te voegen
  docker/src/main/docker/tomcat_conf/server.xml
Labels: functie wens, PostgreSQL
