Repository B3Partners/brmo, pull requests merged in 2024-11, with the labels that each got.

#2283 [BRMO-380] Oracle view vb_util_zk_recht_op_koz toont niet alle zakelijk rechten
  datamodel/brk/brk2.0_oracle_views.sql
  datamodel/upgrade_scripts/3.0.2-4.0.0/oracle/brk.sql
Labels: bug, Oracle

#2302 Bump quartz.version from 2.3.2 to 2.4.0
  pom.xml
Labels: dependency update

#2090 [BRMO-352] - Toevoegen van nHr-views
  brmo-dist/assembly.xml
  datamodel/extra_scripts/oracle/211_nhr_views.sql
  datamodel/extra_scripts/postgresql/211_nhr_views.sql
  docker/src/main/docker/Dockerfile
Labels: functie wens, needs work

#2282 [BRMO-379] [BRMO-332] [BRMO-381] Aanpassingen aan BRK datamodel en BAG/BRK combinatieviews
  datamodel/brk/brk2.0_oracle.sql
  datamodel/brk/brk2.0_postgresql.sql
  datamodel/extra_scripts/oracle/209_bag2_rsgb_views.sql
  datamodel/extra_scripts/postgresql/209_bag2_rsgb_views.sql
  datamodel/src/test/java/nl/b3p/brmo/datamodel/MaterializedViewsTest.java
  datamodel/upgrade_scripts/3.0.2-4.0.0/oracle/brk.sql
  datamodel/upgrade_scripts/3.0.2-4.0.0/oracle/rsgb.sql
  datamodel/upgrade_scripts/3.0.2-4.0.0/postgresql/brk.sql
  datamodel/upgrade_scripts/3.0.2-4.0.0/postgresql/rsgb.sql
Labels: bug, functie wens, needs work, deprecated

#2303 [BRMO-383] voeg kolommen `tijdstipaanbieding_stuk` en `tijdstipaanbieding2` toe aan views
  datamodel/extra_scripts/oracle/210_bag2_brk2.0_mat_views.sql
  datamodel/extra_scripts/postgresql/210_bag2_brk2.0_mat_views.sql
  datamodel/upgrade_scripts/3.0.2-4.0.0/oracle/rsgb.sql
  datamodel/upgrade_scripts/3.0.2-4.0.0/postgresql/rsgb.sql
Labels: functie wens, rsgb

#2313 [BRMO-385] Upgrade GeoTools 32.0 ⇥ 32.1
  pom.xml
Labels: dependency update

#2310 [BRMO-384] Fix Resolving XML external entity in user-controlled data
  brmo-loader/src/main/java/nl/b3p/brmo/loader/xml/BRPXMLReader.java
  brmo-loader/src/main/java/nl/b3p/brmo/loader/xml/Brk2SnapshotXMLReader.java
  brmo-loader/src/main/java/nl/b3p/brmo/loader/xml/BrkSnapshotXMLReader.java
  brmo-loader/src/main/java/nl/b3p/brmo/loader/xml/GbavXMLReader.java
  brmo-loader/src/main/java/nl/b3p/brmo/loader/xml/NhrXMLReader.java
  brmo-loader/src/main/java/nl/b3p/brmo/loader/xml/WozXMLReader.java
Labels: bug, security

#2317 [BRMO-374|BRMO-231] Opruimen BRK 1 transformatie xsl en aanliggende code
  brmo-loader/src/main/java/nl/b3p/brmo/loader/BrmoFramework.java
  brmo-loader/src/main/java/nl/b3p/brmo/loader/RsgbProxy.java
  brmo-loader/src/main/java/nl/b3p/brmo/loader/StagingProxy.java
  brmo-loader/src/main/java/nl/b3p/brmo/loader/entity/BrkBericht.java
  brmo-loader/src/main/java/nl/b3p/brmo/loader/xml/BrkSnapshotXMLReader.java
  brmo-loader/src/main/resources/xsl/brk-snapshot-to-rsgb-xml.xsl
  brmo-loader/src/main/resources/xsl/update-brondocument.xsl
  brmo-loader/src/main/resources/xsl/update-bsn.xsl
  brmo-loader/src/main/resources/xsl/update-comfort-adres.xsl
  brmo-loader/src/main/resources/xsl/update-incompleetadres.xsl
  brmo-loader/src/main/resources/xsl/update-niet_ingezetene-clazz.xsl
  brmo-loader/src/main/resources/xsl/update-rsin.xsl
  brmo-loader/src/main/resources/xsl/update-zak_recht-begindatum.xsl
  brmo-loader/src/main/resources/xsl/update-zak_recht-vve.xsl
  brmo-persistence/src/main/java/nl/b3p/brmo/persistence/staging/BRKScannerProces.java
  brmo-persistence/src/main/resources/META-INF/persistence.xml
  brmo-persistence/src/test/java/nl/b3p/brmo/persistence/staging/BRK2ScannerProcesTest.java
  brmo-persistence/src/test/resources/META-INF/persistence.xml
  brmo-proxyservice/src/main/java/nl/b3p/brmo/service/proxy/BerichtEndpointFileServlet.java
  brmo-proxyservice/src/main/java/nl/b3p/brmo/service/proxy/BerichtEndpointProxyServlet.java
  brmo-proxyservice/src/main/webapp/WEB-INF/web.xml
  brmo-proxyservice/src/test/java/nl/b3p/brmo/service/proxy/BerichtEndpointFileServletTest.java
  brmo-service/src/main/java/nl/b3p/brmo/service/scanner/AbstractExecutableProces.java
  brmo-service/src/main/java/nl/b3p/brmo/service/scanner/BRKDirectoryScanner.java
  brmo-service/src/main/java/nl/b3p/brmo/service/scanner/GDS2OphalenProces.java
  brmo-service/src/main/java/nl/b3p/brmo/service/scanner/ProcesExecutable.java
  brmo-service/src/main/java/nl/b3p/brmo/service/stripes/AdvancedFunctionsActionBean.java
  brmo-service/src/main/java/nl/b3p/brmo/service/stripes/OphaalConfigActionBean.java
  brmo-service/src/main/java/nl/b3p/brmo/service/stripes/UpdatesActionBean.java
  brmo-service/src/main/webapp/WEB-INF/jsp/beheer/editgds2proces.jsp
  brmo-service/src/main/webapp/WEB-INF/jsp/beheer/processenophalen.jsp
  brmo-service/src/main/webapp/WEB-INF/jsp/bestand/form.jsp
  brmo-service/src/main/webapp/WEB-INF/web.xml
  brmo-service/src/test/java/nl/b3p/brmo/service/testutil/TestUtil.java
  brmo-test-util/src/test/resources/web-invalid-jee6.xml
  brmo-test-util/src/test/resources/web-valid-jee6.xml
  brmo-test-util/src/test/resources/web-valid-jee7.xml
  brmo-test-util/src/test/resources/web-valid-jee8.xml
  datamodel/upgrade_scripts/4.0.0-5.0.0/oracle/staging.sql
  datamodel/upgrade_scripts/4.0.0-5.0.0/postgresql/staging.sql
  docker/src/main/docker/Dockerfile
  docker/src/main/docker/tomcat_conf/Catalina/localhost/ROOT.xml
Labels: BRK, brmo-service, brmo-commandline, deprecated
